apiVersion: v1
kind: Pod
metadata:
  name: pod-value-from
  namespace: configmap
spec:
  containers:
    - name: pod-value-from
      image: nginx
      env:
        - name: LIVES_KEY
          valueFrom:
            configMapKeyRef:
              name: game-env-file.properties
              key: lives
        - name: COLOR_KEY
          valueFrom:
            configMapKeyRef:
              name: ui-env-file.properties
              key: color
