apiVersion: v1
kind: Pod
metadata:
  name: liveness-tcp-pod-2
  namespace: probes
  labels:
    live: probe
spec:
  containers:
  - name: liveness-tcp-pod-2
    image: httpd
    ports:
    - containerPort: 80
    readinessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
    livenessProbe:
      tcpSocket:
        port: 82
      initialDelaySeconds: 15
      periodSeconds: 20

---

apiVersion: v1
kind: Service
metadata:
  name: liveness-tcp-svc-2
  namespace: probes
  labels:
    live: probe
spec:
  selector:
    live: probe
  ports:
    - protocol: TCP
      port: 80