apiVersion: v1
kind: Pod
metadata:
  name: liveness-http-pod
  namespace: probes
  labels:
    live: probe
spec:
  containers:
  - name: liveness-http
    image: mcr.microsoft.com/azuredocs/aci-helloworld
    command:
      - "sh"
      - "-c"
      - "node /usr/src/app/index.js & (sleep 180; rm /usr/src/app/index.html);"
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 2 #Default 0
      periodSeconds: 5 #Default 10
      timeoutSeconds: 1 #Default 1
      successThreshold: 1 #Default 1
      failureThreshold: 3 #Default 3

---

apiVersion: v1
kind: Service
metadata:
  name: liveness-http-svc
  namespace: probes
  labels:
    live: probe
spec:
  selector:
    live: probe
  ports:
    - port: 80