apiVersion: v1
kind: Pod
metadata:
  labels:
    ready: probe
  name: practica-readiness-tcp-pod
spec:
  containers:
  - name: ready
    image: mcr.microsoft.com/azuredocs/aci-helloworld
    command:
      - "sh"
      - "-c"
      - "sleep 90; node /usr/src/app/index.js; sleep 1d"
