apiVersion: v1
kind: Pod
metadata:
  labels:
    ready: probe
  name: readiness-command-pod
  namespace: probes
spec:
  containers:
  - name: readiness-command
    image: mcr.microsoft.com/azuredocs/aci-helloworld
    command:
      - "/bin/sh"
      - "-c"
      - "node /usr/src/app/index.js & (sleep 120; touch /tmp/ready); sed -i '16d' /usr/src/app/index.html; sed -i '16i <h1>Now that the container has passed the readiness probe, the web page works wonderfully!</h1>' /usr/src/app/index.html; wait"
    readinessProbe:
      exec:
        command:
        - "cat"
        - "/tmp/ready"
      periodSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: readiness-command-svc
  namespace: probes
  labels:
    ready: probe
spec:
  selector:
    ready: probe
  ports:
    - protocol: TCP
      port: 80
  type: LoadBalancer