apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc
  namespace: service
  labels:
    app: my-app-nodeport
spec:
  selector:
    app: my-app-nodeport
  ports:
    - port: 80
      targetPort: 80
  type: NodePort