apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-nodeport
  namespace: service
spec:
  selector:
    matchLabels:
      app: my-app-nodeport
  replicas: 2
  template:
    metadata:
      labels:
        app: my-app-nodeport
    spec:
      initContainers:
      - name: index-editting
        image: alpine
        command: ["sh","-c","cd /usr/local/apache2/htdocs/; echo '<html><body><h1>' > index.html;  echo 'Configuracion del servicio del tipo: [ NodePort ] exitosa!' >> index.html; echo '</h1></body></html>'  >> index.html"]
        volumeMounts:
        - name: volume-index
          mountPath: /usr/local/apache2/htdocs/
      containers:
      - name: my-app-nodeport
        image: httpd
        volumeMounts:
        - name: volume-index
          mountPath: /usr/local/apache2/htdocs/
      volumes:
        - name: volume-index
          emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc
  namespace: service
  labels:
    app: my-app-nodeport
spec:
  selector:
    app: my-app-nodeport
  ports:
    - port: 80
      targetPort: 80
  type: NodePort