apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-2
spec:
  selector:
    matchLabels:
      app: my-app-2
  replicas: 5
  template:
    metadata:
      labels:
        app: my-app-2
    spec:
      containers:
      - name: my-app-2
        image: httpd
        volumeMounts:
        - name: volume-index
          mountPath: /usr/local/apache2/htdocs/
      - name: create-index-file
        image: alpine
        command: ["sh", "-c","cd /usr/local/apache2/htdocs/; echo '<html><body><h1>' > index.html;  echo Pod ID: $MY_POD_NAME >> index.html; echo '</h1></body></html>'  >> index.html; sleep 50d"]
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        volumeMounts:
        - name: volume-index
          mountPath: /usr/local/apache2/htdocs/
      volumes:
        - name: volume-index
          emptyDir: {}

---

apiVersion: v1
kind: Service
metadata:
  name: service-2
spec:
