apiVersion: v1
kind: Pod
metadata:
  name: pod-value-from-secret
  namespace: secrets
spec:
  containers:
    - name: pod-value-from-secret
      image: redis
      env:
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: from-literal-secret
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: from-literal-secret
              key: password
        - name: SECRET_HOSTNAME
          valueFrom:
            secretKeyRef:
              name: from-env-file-secret
              key: hostname
