apiVersion: v1
kind: Pod
metadata:
  name: pod-secret-volume
  namespace: secrets
spec:
  containers:
  - name: pod-secret-volume
    image: nginx
    volumeMounts:
    - name: secret-volume
      mountPath: /etc/secret
    - name: secret-volume2
      mountPath: /etc/secret2
  volumes:
  - name: secret-volume
    secret:
      secretName: from-file-secret
  - name: secret-volume2
    secret:
      secretName: from-env-file-secret