apiVersion: v1
kind: Pod
metadata:
  name: pod-envfrom-secret
  namespace: secrets
spec:
  containers:
    - name: pod-envfrom-secret
      image: nginx
      envFrom:
      - secretMapRef:
          name: from-file-secret
