apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
spec:
  initContainers:
  - name: file-creator
    image: alpine
    command: [ "sh", "-c", "touch /etc/secret/secret-init-file; echo 'This is the Mysql database name: DB name $VAR' > /etc/secret/secret-init-file; " ]
    volumeMounts:
    - name: init
      mountPath: "/etc/secret"
  containers:
  - name: mysql
    image: mysql
    volumeMounts:
    - name: init
      mountPath: "/etc/secret"
  volumes:
  - name: init
    emptyDir: {}
